### ISSUE TITLE
/etc/sudoers.d has different permissions than sudo package provided by Slackware

### ISSUE THREAD

**Issue by ErichRitz** [aclemons/slackrepo#3]
Slackware's sudo-1.9.14p2-x86_64-1_slack15.0 package installs /etc/sudoers.d/ with permission 750, but slackrepo installs /etc/sudoers.d/ with permission 755.

I don't know if this is a big deal or not.  /etc/sudoers (from package sudo) is 640 and /etc/sudoers.d/slackrepo (from slackrepo) is also 640.

I don't see anything in sudo.SlackBuild that explicitly sets the permission on /etc/sudoers.d, so it must be set that way from upstream.

Edit: if you're wondering how I found this, I use etckeeper and it highlighted the change after upgrading slackrepo.

**Comment by aclemons** [comment]
Thanks for pointing this out. I'll update the slackbuild.

I also need to check on some of the other features idlemoor had in the package too - I think there is a fork of makepkg etc - I don't currently use any of the reproducible build stuff nor the fakeroot stuff (or even the sudo stuff). So I had thought about pruning some of it out. Not sure if any others do use it though.

**Comment by ErichRitz** [comment]
No, I don't use the reproducible build stuff nor fakeroot.  Take it out and see if anyone complains :)

**Comment by aclemons** [comment]
The permissions should be correct with https://github.com/SlackBuildsOrg/slackbuilds/commit/f5d75f17981f48c2217c003d779d74a5093a84cd. Could you confirm that it looks fine for you too?

**Comment by ErichRitz** [comment]
Yes, that fixes it.  Thank you!
